-- Run this only when these tables do not already exist.
-- The existing Supabase companies/data_centers tables should be preserved.
create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  company_code text,
  name text not null,
  industry text,
  country text,
  website text,
  description text,
  renewable_commitment text,
  pue_global_2025 real,
  wue_global_2025 real,
  created_at timestamptz default now()
);

create table if not exists public.data_centers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  data_center_code text not null,
  name text not null,
  location text not null,
  country text not null,
  region text not null,
  pue_2025 real,
  wue_2025 real,
  cpu_capacity real,
  memory_capacity_gb real,
  status text not null default 'active',
  source_name text,
  source_year integer,
  source_url text,
  data_confidence text,
  created_at timestamptz default now()
);

create index if not exists data_centers_company_id_idx
  on public.data_centers(company_id);
