create table if not exists public.companies (
  id bigint primary key,
  company_code text,
  name text not null,
  industry text,
  country text,
  website text,
  description text,
  renewable_commitment text,
  pue_global_2025 real,
  wue_global_2025 real,
  created_at timestamptz default now()
);

create table if not exists public.data_centers (
  id bigint generated by default as identity primary key,
  company_id bigint not null references public.companies(id) on delete cascade,
  data_center_code text not null unique,
  name text not null,
  location text not null,
  country text not null,
  region text not null,
  pue_2025 real,
  wue_2025 real,
  cpu_capacity real,
  memory_capacity_gb real,
  status text not null default 'active',
  source_name text,
  source_year integer,
  source_url text,
  data_confidence text,
  created_at timestamptz default now()
);

insert into public.companies (id, company_code, name, country, description)
values
  (1, 'MS', 'Microsoft', 'United States', 'Microsoft cloud and data-center infrastructure.'),
  (2, 'AWS', 'Amazon Web Services', 'United States', 'AWS cloud and data-center infrastructure.'),
  (3, 'GOOGLE', 'Google Cloud', 'United States', 'Google Cloud infrastructure.'),
  (4, 'META', 'Meta', 'United States', 'Meta data-center infrastructure.')
on conflict (id) do update set
  company_code = excluded.company_code,
  name = excluded.name,
  country = excluded.country,
  description = excluded.description;

create index if not exists data_centers_company_id_idx
  on public.data_centers(company_id);

alter table public.companies enable row level security;
alter table public.data_centers enable row level security;

do $$
begin
  create policy "Public can read companies"
    on public.companies for select to anon, authenticated using (true);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create policy "Public can read data centers"
    on public.data_centers for select to anon, authenticated using (true);
exception
  when duplicate_object then null;
end $$;
